AWSTemplateFormatVersion: "2010-09-09"
Description: Create private S3 bucket for Lambda deployment

Resources:
  LambdaDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-lambda-deployment-${AWS::AccountId}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaDeploymentBucketName:
    Description: Name of the Lambda deployment bucket
    Value: !Ref LambdaDeploymentBucket
