AWSTemplateFormatVersion: "2010-09-09"
Description: Deprecated monolithic template — use src/network.yaml, src/data.yaml, and src/app.yaml with the GitHub Actions workflow.

Metadata:
  Notes:
    - This template is intentionally empty to avoid confusion and accidental use.
    - Network resources: src/network.yaml
    - Data (DocumentDB): src/data.yaml
    - App (Lambda + API Gateway): src/app.yaml
    - CI/CD: .github/workflows/deploy-aws-lambda.yml

Resources: {}

Outputs:
  Notice:
    Description: This stack is a no-op. Please deploy the modular stacks instead.
    Value: "Use src/network.yaml, src/data.yaml, src/app.yaml"
