AWSTemplateFormatVersion: "2010-09-09"
Description: Data Attach stack (attaches Lambda ingress to existing DocumentDB)

Parameters:
  ExistingDocDBClusterIdentifier:
    Type: String
  ExistingDocDBClusterEndpoint:
    Type: String
  ExistingDocDBSecurityGroupId:
    Type: String
  BastionSecurityGroupId:
    Type: String
    Default: ""
    Description: Optional - Security Group ID of a bastion host to allow DocDB access

Conditions:
  HasBastion: !Not [!Equals [!Ref BastionSecurityGroupId, ""]]

Resources:
  AllowLambdaToExistingDocDBIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ExistingDocDBSecurityGroupId
      IpProtocol: tcp
      FromPort: 27017
      ToPort: 27017
      SourceSecurityGroupId: !ImportValue 'hsqbo:network:LambdaSecurityGroupId'

  AllowBastionToExistingDocDBIngress:
    Condition: HasBastion
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ExistingDocDBSecurityGroupId
      IpProtocol: tcp
      FromPort: 27017
      ToPort: 27017
      SourceSecurityGroupId: !Ref BastionSecurityGroupId

Outputs:
  DocDBClusterEndpoint:
    Value: !Ref ExistingDocDBClusterEndpoint
  DocDBClusterIdentifierOut:
    Value: !Ref ExistingDocDBClusterIdentifier
