AWSTemplateFormatVersion: "2010-09-09"
Description: Data Create stack (creates DocumentDB) for HubSpot-QuickBooks backend

Parameters:
  DocDBMasterUsername:
    Type: String
    Default: hubspot_quickbooks_user
  DocDBInstanceClass:
    Type: String
    Default: db.t3.medium
  DocDBClusterIdentifier:
    Type: String
    Default: quickbooks-hubspot-cluster

Resources:
  DocDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DocumentDB access from Lambda
      VpcId: !ImportValue 'hsqbo:network:VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          SourceSecurityGroupId: !ImportValue 'hsqbo:network:LambdaSecurityGroupId'

  DocDBSubnetGroup:
    Type: AWS::DocDB::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for DocumentDB
      SubnetIds:
        - !ImportValue 'hsqbo:network:PrivateSubnet1Id'
        - !ImportValue 'hsqbo:network:PrivateSubnet2Id'

  DocDBCluster:
    Type: AWS::DocDB::DBCluster
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      MasterUsername: !Ref DocDBMasterUsername
      MasterUserPassword: !Sub "{{resolve:secretsmanager:docdb/password:SecretString:password}}"
      DBClusterIdentifier: !Ref DocDBClusterIdentifier
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 07:00-09:00
      VpcSecurityGroupIds:
        - !Ref DocDBSecurityGroup
      DBSubnetGroupName: !Ref DocDBSubnetGroup
      EngineVersion: 5.0
      EnableCloudwatchLogsExports:
        - audit
        - profiler

  DocDBInstance:
    Type: AWS::DocDB::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DocDBCluster
      DBInstanceClass: !Ref DocDBInstanceClass

Outputs:
  DocDBClusterEndpoint:
    Value: !GetAtt DocDBCluster.Endpoint
  DocDBClusterIdentifierOut:
    Value: !Ref DocDBClusterIdentifier
  DocDBSecurityGroupId:
    Value: !Ref DocDBSecurityGroup
