AWSTemplateFormatVersion: "2010-09-09"
Description: Data Attach stack (attaches Lambda ingress to existing DocumentDB)

Parameters:
  Env:
    Type: String
    Default: prod
  ExistingDocDBClusterIdentifier:
    Type: String
  ExistingDocDBClusterEndpoint:
    Type: String
  ExistingDocDBSecurityGroupId:
    Type: String

Resources:
  AllowLambdaToExistingDocDBIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ExistingDocDBSecurityGroupId
      IpProtocol: tcp
      FromPort: 27017
      ToPort: 27017
      SourceSecurityGroupId:
        Fn::ImportValue: !Sub 'hsqbo:${Env}:network:LambdaSecurityGroupId'

Outputs:
  DocDBClusterEndpoint:
    Value: !Ref ExistingDocDBClusterEndpoint
  DocDBClusterIdentifierOut:
    Value: !Ref ExistingDocDBClusterIdentifier
