AWSTemplateFormatVersion: "2010-09-09"
Description: Create Secrets Manager secrets for HubSpot-QuickBooks backend (bootstrap once)

Resources:
  DataBasePasswordSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: docdb/password
      Description: Database Password for DocumentDB (set value after creation)

  ServiceApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: service/api/key
      Description: API Key for Backend Service (set value after creation)

  QuickbookClientIdSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: quickbooks/client/id
      Description: QuickBooks Client ID (set value after creation)

  QuickbookClientKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: quickbooks/client/secret
      Description: QuickBooks Client Secret (set value after creation)

  HubspotApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Name: hubspot/api/key
      Description: HubSpot Private App Token (set value after creation)

Outputs:
  DocDBPasswordSecretName:
    Value: docdb/password
    Description: Name of the DocumentDB password secret
  ServiceApiKeySecretName:
    Value: service/api/key
    Description: Name of the service API key secret
  QuickBooksClientIdSecretName:
    Value: quickbooks/client/id
    Description: Name of the QuickBooks client ID secret
  QuickBooksClientSecretName:
    Value: quickbooks/client/secret
    Description: Name of the QuickBooks client secret
  HubSpotApiKeySecretName:
    Value: hubspot/api/key
    Description: Name of the HubSpot API key secret
